# Generated by Django 5.0.4 on 2024-04-21 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите имя', max_length=150, verbose_name='Имя')),
                ('contact_data', models.CharField(blank=True, help_text='Введите предпочтительный контакт для связи', max_length=220, null=True, verbose_name='Контакты для связи')),
                ('specialty', models.CharField(help_text='Вы по специальности', max_length=150, verbose_name='Специальность')),
                ('info', models.TextField(help_text='Введите дополнительную информацию о Вас', verbose_name='Информация о Вас')),
            ],
            options={
                'verbose_name': 'Заказчик',
                'verbose_name_plural': 'Заказчики',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProviderProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите имя', max_length=150, verbose_name='Имя')),
                ('contact_data', models.CharField(blank=True, help_text='Введите предпочтительный контакт для связи', max_length=220, null=True, verbose_name='Контакты для связи')),
                ('specialty', models.CharField(help_text='Вы по специальности', max_length=150, verbose_name='Специальность')),
                ('info', models.TextField(help_text='Введите дополнительную информацию о Вас', verbose_name='Информация о Вас')),
                ('experience_in_years', models.IntegerField(default=0, help_text='Введите свой опыт работы в годах', verbose_name='Опыт работы (лет)')),
            ],
            options={
                'verbose_name': 'Исполнитель',
                'verbose_name_plural': 'Исполнители',
                'ordering': ['name'],
            },
        ),
    ]
